In [6]:
arr = [1,2,3]

print(arr * 5)

arr = [x*5 for x in arr]

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [7]:
import numpy as np

arr_1 = np.array([1,2,3])

arr_1 = arr_1 * 5
print(arr_1)

[ 5 10 15]


## Ndarray

In [8]:
import numpy as np

# 1D array
arr1 = np.array([1,2,3,4,5])

print(type(arr1))
#show dimention
print(arr1.ndim)

# 2d array

arr2 = np.array([ [1,2,3], #row-1
                  [4,5,6] #row-2
                ])

print(arr2.ndim)


#3d array  

arr3 = np.array([
#first floor
[ [1,2,3], #row-1
[4,5,6] ] ,#row-2
                
#2nd floor

[ [7,8,9], #row-1
[10, 11, 12.5] ] #row-2

])

print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


### array atributes

In [9]:
#dimention
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


#data types
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#size
print(arr1.size)
print(arr2.size)
print(arr3.size)


1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
float64
5
6
12


### ndarray data type

In [10]:
arr = np.array([1,2,3])

print(arr.dtype)


#upcasting
#upcasted to float
arr = np.array([1,2,3.5])
#upcasted to string
arr = np.array([1,2,3.5, '3'])
print(arr.dtype)


int64
<U32


### selecting a data type for an array

In [11]:
arr = np.array([1,2,3], dtype=np.int8)
# arr = np.array([1,2,300], dtype=np.int8)
arr = np.array([1,2,300], dtype=np.int16)
print(arr.dtype)
print(arr)

int16
[  1   2 300]


In [12]:
arr = np.array([1,2,300])
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr.dtype)

int64
int16


In [13]:
arr = np.array([1,2,300], dtype=np.int16)
print(arr.dtype)
print(arr)

arr = arr.astype(np.int32)
print(arr.dtype)


#error
# arr = np.array([1,2,3.5, 'hello'], dtype= np.float64)


int16
[  1   2 300]
int32


## ndarray creation from existing data 

In [14]:
#list

lst = [10, 20, 30, 40, 40.5]

arr = np.array(lst, dtype= np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)


mixed_list = [10, True, 10.5, 'Hello']

arr = np.array(mixed_list)

# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = [ [1,2,3], #row-1
           [4,5,6] #row-2
         ]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [15]:
#tuple

tpl = (1,2,3)

arr = np.array(tpl)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


In [16]:
#set

st = {1,2,3}

arr = np.array(list(st))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


In [20]:
#dictionary 

dc = {
    'a' : 10,
    'b' : 20,
    'c' : 30
}

keys = dc.keys()
values = dc.values()
items = dc.items()

#keys to ndarray
# arr = arr.astype(np.int16)
arr = np.array(list(keys))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

# print(keys)
# print(values)
# print(items)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1


In [26]:
# values to ndarray

arr = np.array(list(values))
arr = arr.astype(np.int16)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)



[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [ ]:
#items to ndarray

arr = np.array(list(items))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


## ndarray creation from scratch

In [33]:
#function: np.zeros()

arr = np.zeros((2,3), dtype= np.int8)


# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr_3 = np.zeros_like(arr3)
print(arr_3)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [42]:
#np.ones()

arr = np.ones((2,3), dtype= np.int8)


# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr_3 = np.ones_like(arr3)
print(arr_3)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [46]:
#np.empty()

arr_ay = np.empty((4,3), dtype= np.int8)


print(arr_ay)
print(type(arr_ay))
print(arr_ay.dtype)
print(arr_ay.shape)
print(arr_ay.ndim)
print(arr_ay.size)

[[97  0  0]
 [ 0 98  0]
 [ 0  0 99]
 [ 0  0  0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12


In [57]:
#np.full()

arr_ay = np.full((4,3),np.inf)


# print(arr_ay)
# print(type(arr_ay))
# print(arr_ay.dtype)
# print(arr_ay.shape)
# print(arr_ay.ndim)
# print(arr_ay.size)

arrP = np.full_like(arr3, np.inf)
print(arrP)
print(arrP.shape)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(2, 2, 3)


### array creation with random values

In [ ]:
#np.random.rand(shape)

arr_ay = np.random.rand(2,3)


print(arr_ay)
print(type(arr_ay))
print(arr_ay.dtype)
print(arr_ay.shape)
print(arr_ay.ndim)
print(arr_ay.size)

[[0.35842922 0.63338882 0.08683514]
 [0.06910791 0.12342391 0.54397555]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [78]:
#np.random.randint(value,shape)

arr_ay = np.random.randint(1,10, (2,3))


print(arr_ay)
print(type(arr_ay))
print(arr_ay.dtype)
print(arr_ay.shape)
print(arr_ay.ndim)
print(arr_ay.size)

[[2 7 1]
 [5 2 7]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [79]:
#np.random.uniform()

arr_ay = np.random.uniform(50,100, (3,4))


print(arr_ay)
print(type(arr_ay))
print(arr_ay.dtype)
print(arr_ay.shape)
print(arr_ay.ndim)
print(arr_ay.size)

[[57.90428963 95.45957561 56.91901966 61.23363316]
 [75.99918169 56.47601896 62.05139609 73.68927958]
 [92.04120262 89.79214289 64.62000253 95.00576277]]
<class 'numpy.ndarray'>
float64
(3, 4)
2
12


## array creation with range function

In [83]:
#np.arange(first, end, step) -> similar to range function

arr = np.arange(1, 10, 1).reshape(3,3)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


In [86]:
#np.linspace(start, stop, num)

arr = np.linspace(1, 10, 15)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
<class 'numpy.ndarray'>
float64
(15,)
1
15


In [90]:
#np.logspace(start, stop, num, base=10)

arr = np.logspace(0, 4, 5)
print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
